
DEPTH           = ../../../../..
topsrcdir       = ../../../../..
srcdir          = .
VPATH           = .

include $(DEPTH)/config/autoconf.mk

MODULE		= tungsten
XPIDL_MODULE    = tungsten
GRE_MODULE	= 1

XPIDLSRCS	= \
		nsIWSRequest.idl \
		$(NULL)

include $(topsrcdir)/config/rules.mk
