//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FlickrUploader.rc
//
#define IDS_PROJNAME                    100
#define IDR_FLICKRUPLOADER              101
#define IDR_SHELLEXTINTERFACE           102
#define WM_FILE_UPLOAD_DONE             103
#define WM_CREATE_NEW_SET               104
#define WM_ADD_TO_SET                   105
#define WM_ADD_TO_FAVORITES             106
#define WM_CREATE_NEW_SET_DONE          108
#define WM_WAIT_ANIMATION_MESSAGE       109
#define WM_RESTORE_USER_DONE            110
#define WM_GET_FROB_DONE                111
#define IDM_SETTINGS                    112
#define WM_CREATE_NEW_USER_DONE         114
#define WM_UPDATE_UPLOAD_STATUS_DONE    115
#define IDB_CON_MENU_BITMAP_WS          202
#define IDC_EDIT_TITLE                  203
#define IDD_DIALOG_FILE_UPLOADER        203
#define IDC_EDIT_DESCRIPTION            205
#define IDB_BITMAP1                     210
#define IDC_COMBO_SAFETY_LEVEL          215
#define IDC_COMBO_HIDDEN                216
#define IDB_BITMAP3                     216
#define IDC_COMBO_CONTENT_TYPE          217
#define IDB_BITMAP4                     217
#define IDC_CHECK_FRIENDS               218
#define IDB_BITMAP5                     218
#define IDC_CHECK_FAMILY                219
#define IDB_BITMAP6                     219
#define IDC_EDIT_API_KEY                220
#define IDB_BITMAP2                     220
#define IDB_BITMAP_ACCOUNT_ONLINE       220
#define IDB_BITMAP_USER_ONLINE          220
#define IDC_CHECK_REMEMBER_KEY          221
#define IDB_BITMAP7                     221
#define IDB_BITMAP_ACCOUNT_OFFLINE      221
#define IDC_CHECK_ADD_TO_FAVORITES      221
#define IDB_BITMAP_USER_OFFLINE         221
#define IDR_MENU1                       222
#define IDR_CONTEXT_MENU                222
#define IDD_DIALOG_CREATE_NEW_SET       223
#define IDB_BITMAP8                     224
#define IDB_BITMAP_CONNECTION_TIMER     224
#define IDC_BUTTON_API_KEY              225
#define IDB_BITMAP9                     225
#define IDB_BITMAP                      225
#define IDB_BITMAP_HELP                 225
#define IDC_COLLAPSED_MARK              226
#define IDB_BITMAP10                    226
#define IDC_COLLAPSED_TEXT              227
#define IDB_BITMAP11                    227
#define IDB_BITMAP12                    228
#define IDB_BITMAP_TIMER                228
#define IDC_BUTTON_UPLOAD               229
#define IDB_BITMAP13                    229
#define IDB_BITMAP14                    230
#define IDB_BITMAP16                    232
#define IDB_BITMAP18                    234
#define IDC_IMAGE_THUMBNAIL_LC_REF      235
#define IDB_BITMAP19                    235
#define IDC_EDIT_TAGS                   236
#define IDB_BITMAP20                    236
#define IDC_RADIO_ONLY_ME               237
#define IDD_DIALOG1                     237
#define IDC_RADIO_ANYONE                238
#define IDB_BITMAP21                    238
#define IDC_ANIMATE_FILE_UPLOAD         239
#define IDC_FILE_NAME                   240
#define IDC_FILE_SIZE                   241
#define IDB_BITMAP_SET_LIST_ITEM        241
#define IDC_UPLOAD_STATUS               242
#define IDB_BITMAP22                    242
#define IDC_MESSAGE_TEXT                243
#define IDB_BITMAP23                    243
#define IDC_MESSAGE_BITMAP              244
#define IDC_MESSAGE_BITMAP_HELP         244
#define IDB_BITMAP24                    244
#define IDC_BUTTON1                     245
#define IDC_BUTTON_SIGN_IN_OUT          245
#define IDB_BITMAP25                    245
#define IDC_BUTTON_SIGN_IN              245
#define IDC_LIST1                       246
#define IDB_BITMAP26                    246
#define IDB_BITMAP_SET_LIST_ITEM_NEW    246
#define IDC_BUTTON_SIGN_OUT             246
#define IDC_LIST2                       247
#define IDC_BUTTON_READY                247
#define IDB_BITMAP_ERROR                247
#define IDC_WSFC_HOME_LIST_CTRL         247
#define IDC_BUTTON2                     248
#define IDB_BITMAP17                    248
#define IDC_BUTTON3                     249
#define IDB_BITMAP27                    249
#define IDC_CHECK1                      250
#define IDC_BUTTON4                     250
#define IDB_BITMAP28                    250
#define IDB_BITMAP_SUCCESS              250
#define IDC_USERNAME_RECT               251
#define IDB_BITMAP15                    251
#define IDC_USER_PHOTOS_URL_RECT        252
#define IDC_USERNAME_RECT2              252
#define IDB_BITMAP29                    252
#define IDC_USER_PROFILE_URL_RECT       253
#define IDC_USERNAME_RECT3              253
#define IDC_AVAILABLE_QUOTA_RECT        254
#define IDC_USERNAME_RECT4              254
#define IDC_USERNAME_CAPTION            255
#define IDC_USER_PHOTOS_CAPTION         256
#define IDC_USERNAME_CAPTION2           256
#define IDD_DIALOG_SETTINGS             256
#define IDC_USER_PROFILE_CAPTION        257
#define IDC_USERNAME_CAPTION3           257
#define IDB_BITMAP30                    257
#define IDB_BITMAP_CON_MENU_FLICKR      257
#define IDC_AVAILABLE_QUOTA_CAPTION     258
#define IDC_USERNAME_CAPTION4           258
#define IDB_BITMAP31                    258
#define IDB_BITMAP_CON_MENU_WS          258
#define IDC_OFFLINE_MESSAGE             259
#define IDI_ICON1                       259
#define IDC_USER_PHOTOS_URL_CAPTION     260
#define IDI_ICON_FLICKR_PAL_16          260
#define IDC_USER_PROFILE_URL_CAPTION    261
#define IDI_ICON3                       261
#define IDI_ICON_FLICKR_PAL_32          261
#define IDC_BUTTON_ADD_SET              262
#define IDC_BUTTON_REMOVE_SET           263
#define IDC_LIST_AVAILABLE_SETS         264
#define IDC_LIST_SELECTED_SETS          265
#define IDC_EDIT_NAME                   266
#define IDC_AWAIT_MESSAGE               266
#define IDC_OFFLINE_MESSAGE_DETAILS     267
#define IDC_USER_BITMAP                 268
#define IDC_AWAIT_MESSAGE_DETAILS       270
#define IDC_IMAGE_DETAILS_GROUP_BOX     271
#define IDC_TITLE_CAPTION               272
#define IDC_DESCRIPTION_CAPTION         273
#define IDC_TAGS_CAPTION                274
#define IDC_WHO_CAN_SEE_GROUP_BOX       275
#define IDC_SAFETY_LEVEL_CAPTION        276
#define IDC_HIDDEN_CAPTION              277
#define IDC_CONTENT_TYPE_CAPTION        278
#define IDC_AVAILABLE_SETS_CAPTION      279
#define IDC_SELECTED_SETS_CAPTION       280
#define IDC_FILE_NAME_CAPTION           281
#define IDC_FILE_SIZE_CAPTION           282
#define IDC_WAIT_ANIMATION_RECT         284
#define IDC_WAIT_ANIMATION_MESSAGE      285
#define IDC_WAIT_ANIMATION_TITLE        286
#define ID_CONTEXTMENU_CREATENEW        32768
#define ID_CONTEXT_MENU_CREATE_NEW_SET  32769
#define ID_CONTEXTMENU_CREATENEW32770   32770
#define ID_CONTEXTMENU_DELETE           32771
#define ID_CONTEXT_MENU_DELETE          32772
#define ID_CONTEXT_MENU_REMOVE_SET      32773
#define ID_CONTEXT_MENU_ADD_NEW_HOME    32774
#define ID_CONTEXT_MENU_REMOVE_HOME     32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        262
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         287
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
