
DEPTH           = ../..
topsrcdir       = ../..
srcdir          = .
VPATH           = .


include $(DEPTH)/config/autoconf.mk

MODULE		= tungsten 
DIRS            = base build


include $(topsrcdir)/config/rules.mk
