
DEPTH           = ../../../..
topsrcdir       = ../../../..
srcdir          = .
VPATH           = .

include $(DEPTH)/config/autoconf.mk

CCFLAGS		= -g
DIRS            = public src

include $(topsrcdir)/config/rules.mk
